spring:
  application:
    name: hello-rabbitmq
  ## rabbit mq ????
#  rabbitmq:
#    addresses: 172.31.2.20
#    port: 15672
#    username: admin
#    password: admin
#    virtual-host: dev

  ## rabbit mq ????
  rabbitmq:
    addresses: 47.116.68.208
    port: 5672
    username: admin
    password: 123456
    virtual-host: demoHost
    listener:
      simple:
        acknowledge-mode: manual